# Use the prebuilt base image
FROM anujkshatriya/animed-base:v1

WORKDIR /app

# Copy only your changing code (very fast layer)
COPY src/ ./src/
COPY python_worker/ ./python_worker/

# (NO npm install, NO pip install here — already done in base image)

CMD ["node", "src/worker.js"]
